wikiOffVersion=0.1
wiki_person=[('muhammad', 'islam prophet'), ('bill gates', 'big bill')]
wiki_place=[('saudi arabia', 'saudi arab', 'arab'), ('new york city', 'nyc', 'new york city')]
wiki_pla_country=["""all countryz"""]
wiki_pla_city=["""famous cityz"""]
wiki_pla_capital=["""all capitalz"""]
wiki_object=[('quran', 'al quran', 'holy quran'), ('nobel prize', 'noble prize')]
wiki_topic=[('binary number', 'binary'), ('computer', ), ('python', )]
wiki_relig=[('islam', 'peace'), ('muslims', 'muslim', ), ('allah', ), ('hinduism', ), ('hindus', )]
wiki_per_scientist=[('isaac newton', 'issac newton','newton', ), ('einstain', 'aldert einstain'), ('plank', 'max plank'), ('stephen hawking', 'hawking'), ('bekerel', )]
wiki_per_player=[('sakib', 'sakib al hasan')]
wiki_db=[wiki_person, wiki_place, wiki_object, wiki_topic, wiki_relig]
wiki_dbs=('wiki_person', 'wiki_place', 'wiki_object', 'wiki_topic', 'wiki_relig', 'wiki_per_player', 'wiki_per_scientist',)