{
	"countryname":
	"localname":
	"lang":
	"currency_s":
	"currency_l":
	"lat_lon":
	"area":
	"capital":
	"location":
	"population":
	"region":
	"sub_region":
	"famous_place":
	"famous_people":
	"liberation_date":
	"rule_policy":
	"border":
	"GDP":
	"GNP":
	"PCI":
	"edu_rate":
	"PM":
	"President":
	"pop_growth":
	"birth_rate":
	"death_rate":
	"infant_death_rate":
	"poverty_rate":
	"homeless_rate":
	"prine_religions":
	"name_in_diff_lang":
	"official_lang":
	"general_food":
	"gender_discrimination":
	"festivals":
	"phone_index":
	"tnt_index":
	"short_form":
	"natural_resources":
	"land_boundaries":
	"coastline":
	"climate":
	"natural_hazards":
	"environment_current-issues":
	"nationality":
	"ethnic_groups":
}
